[package]
name = "dataragon"
version = "0.0.1"
authors = ["Sergey Tolmachev <tolsi.ru@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
secrets = "0.12.1"
shamirsecretsharing = "0.1"
ring = "0.16.9"
